pluginManagement {
    repositories {
        **ARTIFACTORYREPOSITORY**
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

include ':launcher', ':tuanjieLibrary'
**INCLUDES**

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        **ARTIFACTORYREPOSITORY**
        google()
        mavenCentral()
// Android Resolver Repos Start
        def unityProjectPath = $/file:///**DIR_UNITYPROJECT**/$.replace("\\", "/")
        maven {
            url "https://repo.maven.apache.org/maven2" // Assets/TapTapServer/TapSDK/Compliance/Mobile/Editor/NativeDependencies.xml:6, Assets/TapTapServer/TapSDK/Core/Mobile/Editor/NativeDependencies.xml:6, Assets/TapTapServer/TapSDK/Login/Mobile/Editor/NativeDependencies.xml:6, Assets/TapTapServer/DirichletAd/Editor/DirichletAdDependencies.xml:46, Assets/TapTapServer/DirichletAd/Editor/DirichletAdDependencies.xml:52
        }
        maven {
            url "https://maven.google.com" // Assets/TapTapServer/DirichletAd/Editor/DirichletAdDependencies.xml:21, Assets/TapTapServer/DirichletAd/Editor/DirichletAdDependencies.xml:27, Assets/TapTapServer/DirichletAd/Editor/DirichletAdDependencies.xml:33, Assets/TapTapServer/DirichletAd/Editor/DirichletAdDependencies.xml:39
        }
        mavenLocal()
// Android Resolver Repos End
        flatDir {
            dirs "${project(':tuanjieLibrary').projectDir}/libs"
        }
    }
}
