apply plugin: 'com.android.library'

android {
    namespace "com.unity3d.player"
    compileSdkVersion **APIVERSION**
    buildToolsVersion '**BUILDTOOLS**'

    defaultConfig {
        minSdkVersion **MINSDKVERSION**
    }

    sourceSets {
        main {
            res.srcDirs = ['res']
        }
    }
}

